import React, { useState, useEffect, useRef } from 'react';
import { db } from '../services/mockDb';
import { Loan, LoanStatus, Book, Student, ReturnCondition } from '../types';
import { 
  Plus, Check, Clock, AlertTriangle, User, Book as BookIcon, Calendar, 
  X, Scan, Search, ArrowRight, Save, History, FileText, Download, Wallet
} from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import * as XLSX from 'xlsx';

type Tab = 'borrow' | 'return' | 'records' | 'reports';

export default function LoanManager() {
  const [activeTab, setActiveTab] = useState<Tab>('borrow');
  const [loans, setLoans] = useState<Loan[]>([]);
  const [books, setBooks] = useState<Book[]>([]);
  const [students, setStudents] = useState<Student[]>([]);

  // --- Borrow State ---
  const [selectedStudent, setSelectedStudent] = useState<Student | null>(null);
  const [studentSearch, setStudentSearch] = useState('');
  const [borrowCart, setBorrowCart] = useState<Book[]>([]);
  const [borrowDate, setBorrowDate] = useState(new Date().toISOString().split('T')[0]);
  const [dueDate, setDueDate] = useState(new Date(Date.now() + 14 * 86400000).toISOString().split('T')[0]);
  
  // --- Return State ---
  const [returnScanCode, setReturnScanCode] = useState('');
  const [foundLoan, setFoundLoan] = useState<Loan | null>(null);
  const [returnCondition, setReturnCondition] = useState<ReturnCondition>(ReturnCondition.GOOD);
  const [fineAmount, setFineAmount] = useState(0);

  // --- Barcode Input Ref ---
  const barcodeInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    refreshData();
    // Auto-focus barcode input when switching tabs
    if (activeTab === 'borrow' || activeTab === 'return') {
      setTimeout(() => barcodeInputRef.current?.focus(), 100);
    }
  }, [activeTab]);

  const refreshData = () => {
    setLoans(db.getLoans());
    setBooks(db.getBooks());
    setStudents(db.getStudents());
  };

  const getBookName = (id: string) => books.find(b => b.id === id)?.title || 'Buku Tidak Dikenali';
  const getStudentName = (id: string) => {
    // Check students first
    const student = students.find(s => s.id === id);
    if (student) return student.name;
    // Fallback to borrowers (legacy/teachers)
    const borrower = db.getBorrowers().find(b => b.id === id);
    return borrower ? borrower.name : 'Pengguna Tidak Dikenali';
  };

  const getStudentClass = (id: string) => {
    const student = students.find(s => s.id === id);
    return student ? student.class_name : '-';
  };

  // --- Shared Scanner Handler ---
  const handleScan = (e: React.KeyboardEvent<HTMLInputElement>, mode: 'borrow' | 'return') => {
    if (e.key === 'Enter') {
      const code = e.currentTarget.value.trim();
      if (!code) return;

      // Extract Book ID. Assuming Code128 format is "BK{BookID}-{Seq}" e.g., "BK001-001"
      // Or simple ID "b1"
      let bookId = code;
      
      // Attempt to parse Code128 format generated by our barcode module
      // Format: BK + ID + - + Seq. E.g. BKb1-001 (If id is b1) or BKB001-001
      // For this mock, we'll try to match exact ID first, then fuzzy match.
      
      // Heuristic: If code starts with BK, try to extract ID
      // Real implementation would have a lookup table for unique barcode strings.
      // Here, we look for a book where code includes the ID or ISBN
      let foundBook = books.find(b => b.id === code || b.isbn === code);
      
      if (!foundBook) {
         // Try parsing BK{id}-...
         const potentialId = books.find(b => code.includes(b.id));
         if(potentialId) foundBook = potentialId;
      }

      if (mode === 'borrow') {
        if (foundBook) {
            // Check stock
            if(foundBook.stock <= 0) {
                alert(`Stok buku ${foundBook.title} telah habis!`);
            } else if (borrowCart.find(b => b.id === foundBook!.id)) {
                alert("Buku ini sudah ada dalam senarai pinjaman.");
            } else {
                setBorrowCart([...borrowCart, foundBook]);
            }
        } else {
            alert("Buku tidak dijumpai dalam pangkalan data.");
        }
      } else if (mode === 'return') {
        // Find active loan for this book
        // In real app, we use unique barcode copy ID. Here we use Book ID.
        if (foundBook) {
            const loan = db.findActiveLoanByBook(foundBook.id);
            if (loan) {
                setFoundLoan(loan);
                setReturnCondition(ReturnCondition.GOOD);
                setFineAmount(0);
            } else {
                alert("Tiada rekod pinjaman aktif untuk buku ini.");
            }
        } else {
            alert("Buku tidak dijumpai.");
        }
      }

      e.currentTarget.value = ''; // Clear input for next scan
    }
  };

  // --- Borrow Logic ---
  const confirmBorrow = () => {
    if (!selectedStudent) return alert("Sila pilih murid dahulu.");
    if (borrowCart.length === 0) return alert("Sila imbas sekurang-kurangnya satu buku.");

    borrowCart.forEach(book => {
      const newLoan: Loan = {
        id: Date.now().toString() + Math.random().toString().slice(2,5),
        bookId: book.id,
        borrowerId: selectedStudent.id,
        borrowDate: borrowDate,
        dueDate: dueDate,
        status: LoanStatus.ACTIVE
      };
      
      // Update book stock
      const updatedBook = { ...book, stock: book.stock - 1 };
      db.saveBook(updatedBook);
      db.saveLoan(newLoan);
    });

    alert("Pinjaman berjaya direkodkan!");
    setBorrowCart([]);
    setSelectedStudent(null);
    setStudentSearch('');
    refreshData();
  };

  // --- Return Logic ---
  const confirmReturn = () => {
    if (!foundLoan) return;

    let status = LoanStatus.RETURNED;
    if (returnCondition === ReturnCondition.LOST) status = LoanStatus.LOST;

    // Update Loan
    const updatedLoan: Loan = {
      ...foundLoan,
      status: status,
      returnDate: new Date().toISOString().split('T')[0],
      returnCondition: returnCondition,
      fine: fineAmount
    };
    db.saveLoan(updatedLoan);

    // Update Book Stock/Stats
    const book = books.find(b => b.id === foundLoan.bookId);
    if (book) {
       let newStock = book.stock;
       let newDamaged = book.damaged;
       let newLost = book.lost;

       if (returnCondition === ReturnCondition.GOOD) {
         newStock += 1; // Returned to circulation
       } else if (returnCondition === ReturnCondition.DAMAGED) {
         newDamaged += 1; // Returned but damaged
         // Optionally add to stock if repairable, or keep out. Assuming kept out of stock.
       } else if (returnCondition === ReturnCondition.LOST) {
         newLost += 1; // Lost forever
       }

       db.saveBook({ ...book, stock: newStock, damaged: newDamaged, lost: newLost });
    }

    alert(`Pemulangan berjaya. ${fineAmount > 0 ? `Denda dikenakan: RM${fineAmount.toFixed(2)}` : ''}`);
    setFoundLoan(null);
    setReturnScanCode('');
    refreshData();
    // Refocus scanner
    setTimeout(() => barcodeInputRef.current?.focus(), 100);
  };

  const handleConditionChange = (cond: ReturnCondition) => {
    setReturnCondition(cond);
    if (foundLoan) {
      const book = books.find(b => b.id === foundLoan.bookId);
      if (cond === ReturnCondition.LOST && book) {
        setFineAmount(book.price || 0);
      } else {
        setFineAmount(0);
      }
    }
  };

  // --- Reports Logic ---
  const handleExport = () => {
    const data = loans.map(l => ({
        ID: l.id,
        Buku: getBookName(l.bookId),
        Peminjam: getStudentName(l.borrowerId),
        Kelas: getStudentClass(l.borrowerId),
        Tarikh_Pinjam: l.borrowDate,
        Tarikh_Tamat: l.dueDate,
        Tarikh_Pulang: l.returnDate || '-',
        Status: l.status,
        Kondisi: l.returnCondition || '-',
        Denda: l.fine ? `RM${l.fine}` : '-'
    }));
    const ws = XLSX.utils.json_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Rekod Pinjaman");
    XLSX.writeFile(wb, "SPBT_Laporan_Pinjaman.xlsx");
  };

  // --- UI Components ---
  
  const TabButton = ({ id, label, icon: Icon }: { id: Tab, label: string, icon: any }) => (
    <button 
      onClick={() => setActiveTab(id)}
      className={`flex items-center px-6 py-3 rounded-t-2xl font-medium transition-all ${
        activeTab === id 
          ? 'bg-white/10 text-blue-300 border-b-2 border-blue-400 backdrop-blur-md' 
          : 'text-slate-400 hover:bg-white/5 hover:text-slate-200'
      }`}
    >
      <Icon size={18} className="mr-2" /> {label}
    </button>
  );

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center mb-2">
        <div>
           <h2 className="text-2xl font-bold text-white drop-shadow-lg">Modul Sirkulasi</h2>
           <p className="text-slate-400 text-sm">Peminjaman dan pemulangan automatik berasaskan kod bar.</p>
        </div>
      </div>

      {/* Navigation Tabs */}
      <div className="flex border-b border-white/10 mb-6">
        <TabButton id="borrow" label="Peminjaman" icon={ArrowRight} />
        <TabButton id="return" label="Pemulangan" icon={History} />
        <TabButton id="records" label="Rekod Transaksi" icon={FileText} />
        <TabButton id="reports" label="Analisis & Laporan" icon={BarChart} />
      </div>

      {/* --- BORROW TAB --- */}
      {activeTab === 'borrow' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 animate-fade-in">
           {/* Left: Student Selection */}
           <div className="glass-panel p-6 rounded-2xl h-full">
              <h3 className="text-lg font-bold text-white mb-4 flex items-center">
                 <User className="mr-2 text-blue-400" /> Maklumat Peminjam
              </h3>
              
              <div className="mb-6 relative">
                 <input 
                   type="text" 
                   className="w-full glass-input rounded-xl px-10 py-3"
                   placeholder="Cari Nama / ID / Kelas..."
                   value={studentSearch}
                   onChange={e => setStudentSearch(e.target.value)}
                 />
                 <Search className="absolute left-3 top-3.5 text-slate-400" size={18} />
                 
                 {studentSearch && !selectedStudent && (
                    <div className="absolute top-full left-0 w-full mt-2 bg-slate-900 border border-white/10 rounded-xl shadow-xl z-20 max-h-48 overflow-y-auto">
                        {students.filter(s => s.name.toLowerCase().includes(studentSearch.toLowerCase()) || s.student_id.includes(studentSearch)).map(s => (
                            <div 
                                key={s.id} 
                                onClick={() => { setSelectedStudent(s); setStudentSearch(''); }}
                                className="p-3 hover:bg-white/10 cursor-pointer border-b border-white/5 last:border-0"
                            >
                                <p className="text-white font-medium">{s.name}</p>
                                <p className="text-xs text-slate-400">{s.class_name} • {s.student_id}</p>
                            </div>
                        ))}
                    </div>
                 )}
              </div>

              {selectedStudent ? (
                 <div className="bg-blue-600/20 border border-blue-500/30 p-4 rounded-xl relative overflow-hidden group">
                    <div className="relative z-10">
                        <h4 className="text-xl font-bold text-white">{selectedStudent.name}</h4>
                        <p className="text-blue-200 mt-1">{selectedStudent.class_name}</p>
                        <p className="text-xs text-blue-300/70 mt-4 font-mono">ID: {selectedStudent.student_id}</p>
                    </div>
                    <button 
                       onClick={() => setSelectedStudent(null)} 
                       className="absolute top-2 right-2 p-1.5 bg-black/20 hover:bg-black/40 rounded-full text-white/70 hover:text-white transition"
                    >
                        <X size={14} />
                    </button>
                    {/* Decorative Blob */}
                    <div className="absolute -bottom-10 -right-10 w-32 h-32 bg-blue-500/30 blur-2xl rounded-full"></div>
                 </div>
              ) : (
                 <div className="text-center py-10 border-2 border-dashed border-white/10 rounded-xl text-slate-500">
                    <User size={32} className="mx-auto mb-2 opacity-50" />
                    <p>Sila pilih murid untuk memulakan.</p>
                 </div>
              )}

              <div className="mt-8 space-y-4">
                 <div>
                    <label className="text-xs text-slate-400 uppercase font-bold">Tarikh Pinjam</label>
                    <input type="date" className="w-full glass-input rounded-lg px-3 py-2 mt-1" value={borrowDate} onChange={e => setBorrowDate(e.target.value)} />
                 </div>
                 <div>
                    <label className="text-xs text-slate-400 uppercase font-bold">Tarikh Pulang</label>
                    <input type="date" className="w-full glass-input rounded-lg px-3 py-2 mt-1" value={dueDate} onChange={e => setDueDate(e.target.value)} />
                 </div>
              </div>
           </div>

           {/* Right: Scanner & Cart */}
           <div className="lg:col-span-2 glass-panel p-6 rounded-2xl flex flex-col h-full">
              <div className="flex items-center justify-between mb-6">
                 <h3 className="text-lg font-bold text-white flex items-center">
                    <Scan className="mr-2 text-emerald-400" /> Imbas Buku (Kod Bar)
                 </h3>
                 <span className="text-xs text-emerald-400 bg-emerald-500/10 px-2 py-1 rounded animate-pulse">Scanner Ready</span>
              </div>

              {/* Scanner Input (Always Focused via Ref) */}
              <div className="relative mb-6">
                  <input 
                    ref={barcodeInputRef}
                    type="text" 
                    className="w-full bg-black/30 border border-emerald-500/50 text-emerald-400 font-mono text-lg rounded-xl px-12 py-4 focus:ring-2 focus:ring-emerald-500 outline-none transition-all placeholder-emerald-700/50"
                    placeholder="Imbas kod bar buku di sini..."
                    onKeyDown={(e) => handleScan(e, 'borrow')}
                    disabled={!selectedStudent}
                  />
                  <Scan className="absolute left-4 top-5 text-emerald-500" size={20} />
              </div>

              {/* Cart List */}
              <div className="flex-1 bg-white/5 rounded-xl p-4 overflow-y-auto min-h-[300px]">
                 {borrowCart.length > 0 ? (
                    <div className="space-y-3">
                       {borrowCart.map((book, idx) => (
                          <div key={idx} className="flex items-center justify-between p-3 bg-white/5 rounded-lg border border-white/5 animate-slide-up">
                             <div className="flex items-center gap-3">
                                <div className="p-2 bg-indigo-500/20 rounded-lg text-indigo-300">
                                   <BookIcon size={18} />
                                </div>
                                <div>
                                   <h5 className="font-bold text-white text-sm">{book.title}</h5>
                                   <p className="text-xs text-slate-400 font-mono">{book.isbn}</p>
                                </div>
                             </div>
                             <button 
                               onClick={() => setBorrowCart(borrowCart.filter((_, i) => i !== idx))}
                               className="text-red-400 hover:text-red-300 p-2"
                             >
                                <X size={18} />
                             </button>
                          </div>
                       ))}
                    </div>
                 ) : (
                    <div className="h-full flex flex-col items-center justify-center text-slate-500">
                       <BookIcon size={48} className="mb-4 opacity-20" />
                       <p>Senarai buku kosong.</p>
                       <p className="text-sm opacity-60">Imbas kod bar buku untuk menambah.</p>
                    </div>
                 )}
              </div>

              {/* Action Footer */}
              <div className="mt-6 pt-4 border-t border-white/10 flex justify-between items-center">
                 <div className="text-slate-400 text-sm">
                    Jumlah Buku: <span className="text-white font-bold">{borrowCart.length}</span>
                 </div>
                 <button 
                    onClick={confirmBorrow}
                    disabled={borrowCart.length === 0 || !selectedStudent}
                    className="flex items-center px-8 py-3 bg-gradient-to-r from-emerald-600 to-teal-600 text-white font-bold rounded-xl shadow-lg hover:shadow-emerald-500/20 disabled:opacity-50 disabled:cursor-not-allowed transition transform hover:-translate-y-1"
                 >
                    <Save size={18} className="mr-2" /> Sahkan Pinjaman
                 </button>
              </div>
           </div>
        </div>
      )}

      {/* --- RETURN TAB --- */}
      {activeTab === 'return' && (
         <div className="max-w-4xl mx-auto space-y-8 animate-fade-in">
             {/* Big Scanner Box */}
             <div className="glass-panel p-10 rounded-2xl text-center border-2 border-purple-500/30 bg-purple-900/10">
                 <h2 className="text-3xl font-bold text-white mb-2">Modul Pemulangan</h2>
                 <p className="text-purple-200/70 mb-8">Sila imbas buku untuk memproses pemulangan.</p>
                 
                 <div className="relative max-w-xl mx-auto">
                    <input 
                        ref={barcodeInputRef}
                        type="text" 
                        className="w-full bg-black/40 border-2 border-purple-500 text-purple-300 font-mono text-2xl rounded-2xl px-14 py-6 focus:ring-4 focus:ring-purple-500/30 outline-none transition-all placeholder-purple-700/50 text-center"
                        placeholder="Imbas Sini..."
                        onKeyDown={(e) => handleScan(e, 'return')}
                        value={returnScanCode}
                        onChange={e => setReturnScanCode(e.target.value)}
                    />
                    <Scan className="absolute left-5 top-7 text-purple-500 animate-pulse" size={32} />
                 </div>
             </div>

             {/* Found Loan Details Card */}
             {foundLoan && (
                 <div className="glass-panel p-0 rounded-2xl overflow-hidden animate-slide-up border border-white/20 shadow-2xl">
                     <div className="bg-gradient-to-r from-purple-900/50 to-blue-900/50 p-6 border-b border-white/10 flex justify-between items-start">
                         <div>
                            <h3 className="text-2xl font-bold text-white mb-1">{getBookName(foundLoan.bookId)}</h3>
                            <p className="text-blue-200">ID Pinjaman: #{foundLoan.id}</p>
                         </div>
                         <div className="bg-black/30 px-4 py-2 rounded-lg text-right">
                             <p className="text-xs text-slate-400">Peminjam</p>
                             <p className="text-lg font-bold text-white">{getStudentName(foundLoan.borrowerId)}</p>
                             <p className="text-xs text-slate-400">{getStudentClass(foundLoan.borrowerId)}</p>
                         </div>
                     </div>

                     <div className="p-8 grid grid-cols-1 md:grid-cols-2 gap-8">
                         {/* Dates & Status */}
                         <div className="space-y-4">
                             <div className="flex items-center justify-between p-3 bg-white/5 rounded-lg">
                                <span className="text-slate-400 flex items-center"><Calendar size={16} className="mr-2"/> Tarikh Pinjam</span>
                                <span className="text-white font-mono">{foundLoan.borrowDate}</span>
                             </div>
                             <div className="flex items-center justify-between p-3 bg-white/5 rounded-lg">
                                <span className="text-slate-400 flex items-center"><Clock size={16} className="mr-2"/> Tarikh Patut Pulang</span>
                                <span className="text-white font-mono">{foundLoan.dueDate}</span>
                             </div>
                             {new Date() > new Date(foundLoan.dueDate) && (
                                <div className="flex items-center p-3 bg-red-500/20 text-red-300 rounded-lg border border-red-500/30">
                                   <AlertTriangle size={18} className="mr-2" /> Buku ini lewat dipulangkan!
                                </div>
                             )}
                         </div>

                         {/* Condition & Fine */}
                         <div className="space-y-4">
                             <p className="font-bold text-white mb-2">Kondisi Buku</p>
                             <div className="grid grid-cols-3 gap-2">
                                {[ReturnCondition.GOOD, ReturnCondition.DAMAGED, ReturnCondition.LOST].map(cond => (
                                    <button
                                        key={cond}
                                        onClick={() => handleConditionChange(cond)}
                                        className={`p-3 rounded-xl border text-sm font-bold transition-all ${
                                            returnCondition === cond 
                                            ? 'bg-blue-500 text-white border-blue-400 shadow-lg scale-105' 
                                            : 'bg-white/5 text-slate-400 border-white/10 hover:bg-white/10'
                                        }`}
                                    >
                                        {cond}
                                    </button>
                                ))}
                             </div>
                             
                             {/* Fine Display */}
                             <div className={`mt-4 p-4 rounded-xl border flex justify-between items-center transition-all ${fineAmount > 0 ? 'bg-red-500/10 border-red-500/30' : 'bg-emerald-500/10 border-emerald-500/30'}`}>
                                 <div className="flex items-center">
                                     <Wallet className={`${fineAmount > 0 ? 'text-red-400' : 'text-emerald-400'} mr-3`} size={20} />
                                     <div>
                                        <p className="text-xs text-slate-400 uppercase font-bold">Ganti Rugi / Denda</p>
                                        <p className={`text-xl font-bold ${fineAmount > 0 ? 'text-red-400' : 'text-emerald-400'}`}>
                                            RM {fineAmount.toFixed(2)}
                                        </p>
                                     </div>
                                 </div>
                             </div>
                         </div>
                     </div>

                     <div className="p-6 bg-black/20 border-t border-white/10 flex justify-end">
                         <button onClick={() => setFoundLoan(null)} className="px-6 py-3 mr-3 text-slate-400 hover:text-white">Batal</button>
                         <button 
                            onClick={confirmReturn}
                            className="px-8 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-bold rounded-xl shadow-lg hover:shadow-purple-500/30 transition transform hover:-translate-y-1"
                         >
                            Sahkan Pemulangan
                         </button>
                     </div>
                 </div>
             )}
         </div>
      )}

      {/* --- RECORDS TAB --- */}
      {activeTab === 'records' && (
          <div className="glass-panel rounded-2xl overflow-hidden animate-fade-in">
              <div className="p-4 border-b border-white/10 flex justify-between items-center">
                  <h3 className="font-bold text-white">Sejarah Transaksi</h3>
                  <div className="flex items-center space-x-2 text-xs text-slate-400">
                      <div className="flex items-center"><span className="w-2 h-2 rounded-full bg-blue-500 mr-2"></span> Aktif</div>
                      <div className="flex items-center"><span className="w-2 h-2 rounded-full bg-emerald-500 mr-2"></span> Pulang</div>
                      <div className="flex items-center"><span className="w-2 h-2 rounded-full bg-red-500 mr-2"></span> Lewat</div>
                  </div>
              </div>
              <div className="overflow-x-auto">
                  <table className="w-full text-left text-sm">
                      <thead className="bg-white/5 text-slate-300">
                          <tr>
                              <th className="p-4">ID</th>
                              <th className="p-4">Buku</th>
                              <th className="p-4">Peminjam</th>
                              <th className="p-4">Tarikh</th>
                              <th className="p-4">Status</th>
                          </tr>
                      </thead>
                      <tbody className="divide-y divide-white/5">
                          {loans.map(loan => (
                              <tr key={loan.id} className="hover:bg-white/5">
                                  <td className="p-4 font-mono text-slate-500">#{loan.id.slice(-6)}</td>
                                  <td className="p-4 font-medium text-white">{getBookName(loan.bookId)}</td>
                                  <td className="p-4 text-slate-300">{getStudentName(loan.borrowerId)}</td>
                                  <td className="p-4 text-slate-400">
                                      <div className="flex flex-col text-xs">
                                          <span>Out: {loan.borrowDate}</span>
                                          <span>In: {loan.dueDate}</span>
                                      </div>
                                  </td>
                                  <td className="p-4">
                                      <span className={`px-2 py-1 rounded text-xs font-bold ${
                                          loan.status === LoanStatus.ACTIVE ? 'bg-blue-500/20 text-blue-300' :
                                          loan.status === LoanStatus.RETURNED ? 'bg-emerald-500/20 text-emerald-300' :
                                          'bg-red-500/20 text-red-300'
                                      }`}>
                                          {loan.status}
                                      </span>
                                  </td>
                              </tr>
                          ))}
                      </tbody>
                  </table>
              </div>
          </div>
      )}

      {/* --- REPORTS TAB --- */}
      {activeTab === 'reports' && (
          <div className="space-y-6 animate-fade-in">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  {/* Summary Cards */}
                  <div className="glass-panel p-6 rounded-xl border-l-4 border-blue-500">
                      <p className="text-slate-400 text-xs uppercase font-bold">Jumlah Pinjaman Aktif</p>
                      <h3 className="text-3xl font-bold text-white mt-1">{loans.filter(l => l.status === LoanStatus.ACTIVE).length}</h3>
                  </div>
                  <div className="glass-panel p-6 rounded-xl border-l-4 border-red-500">
                      <p className="text-slate-400 text-xs uppercase font-bold">Buku Hilang / Rosak</p>
                      <h3 className="text-3xl font-bold text-white mt-1">
                          {loans.filter(l => l.status === LoanStatus.LOST || l.returnCondition === ReturnCondition.DAMAGED).length}
                      </h3>
                  </div>
                  <div className="glass-panel p-6 rounded-xl border-l-4 border-emerald-500 flex justify-between items-center cursor-pointer hover:bg-white/5" onClick={handleExport}>
                      <div>
                          <p className="text-slate-400 text-xs uppercase font-bold">Eksport Data</p>
                          <h3 className="text-lg font-bold text-emerald-400 mt-1 flex items-center">
                              <Download size={18} className="mr-2" /> Muat Turun Excel
                          </h3>
                      </div>
                  </div>
              </div>

              {/* Chart */}
              <div className="glass-panel p-6 rounded-2xl h-80">
                  <h4 className="text-white font-bold mb-4">Statistik Pinjaman Mingguan</h4>
                  <ResponsiveContainer width="100%" height="100%">
                      <BarChart data={[
                          { name: 'Isnin', total: 12 },
                          { name: 'Selasa', total: 19 },
                          { name: 'Rabu', total: 3 },
                          { name: 'Khamis', total: 5 },
                          { name: 'Jumaat', total: 2 },
                      ]}>
                          <XAxis dataKey="name" stroke="#64748b" />
                          <YAxis stroke="#64748b" />
                          <Tooltip contentStyle={{backgroundColor: '#0f172a', borderColor: '#334155', color: '#fff'}} />
                          <Bar dataKey="total" fill="#3b82f6" radius={[4, 4, 0, 0]} />
                      </BarChart>
                  </ResponsiveContainer>
              </div>
          </div>
      )}
    </div>
  );
}